[Guardian]
    MnemonicFile = "keys/multiversx.mnemonic" # the path to the file containing the mnemonic phrase
    RequestTimeInSeconds = 2 # maximum timeout (in seconds) for the gas price request

[Proxy]
    NetworkAddress = "https://devnet-gateway.multiversx.com" # the network address
    ProxyCacherExpirationSeconds = 600 # the caching time in seconds

    # valid options for ProxyRestAPIEntityType are `observer` and `proxy`. Any other value will trigger an error.
    # `observer` is useful when querying an observer, directly and `proxy` is useful when querying a squad's proxy
    ProxyRestAPIEntityType = "proxy"
    ProxyFinalityCheck = true
    ProxyMaxNoncesDelta = 7 # the number of maximum blocks allowed to be "in front" of what the metachain has notarized

[Api]
    NetworkAddress = "https://devnet-api.multiversx.com" # the network address

[Logs]
    LogFileLifeSpanInSec = 86400 # 24h

[Antiflood]
    Enabled = true
    [Antiflood.WebServer]
            # SimultaneousRequests represents the number of concurrent requests accepted by the web server
            # this is a global throttler that acts on all http connections regardless of the originating source
            SimultaneousRequests = 100
            # SameSourceRequests defines how many requests are allowed from the same source in the specified
            # time frame (SameSourceResetIntervalInSec)
            SameSourceRequests = 10000
            # SameSourceResetIntervalInSec time frame between counter reset, in seconds
            SameSourceResetIntervalInSec = 1

[ServiceResolver]
    RequestTimeInSeconds = 2
    SkipTxUserSigVerify = true

[ShardedStorage]
    DBType = "levelDB"
    DelayBetweenWritesInSec = 86400 # the time allowed between two successive totp generation
    [ShardedStorage.Users]
        [ShardedStorage.Users.DB]
            FilePath = "UsersDB"
            Type = "LvlDB"
            BatchDelaySeconds = 1
            MaxBatchSize = 1000
            MaxOpenFiles = 10
        [ShardedStorage.Users.Cache]
            Name = "UsersCache"
            Capacity = 100000
            Type = "SizeLRU"
            SizeInBytes = 104857600 # 100MB

[Buckets]
    NumberOfBuckets = 4

[General]
    Marshalizer = "gogo protobuf"

[TwoFactor]
    Issuer = "MultiversX"
    Digits = 6

# NativeAuthServer is the cache that is used to store timestamps of block hashes
[NativeAuthServer]
    [NativeAuthServer.Cache]
        Name = "NativeAuthServer"
        Capacity = 100
        Type = "LRU"
