[General]
    Marshalizer = "gogo protobuf"

    # Defines the storage persister type
    # Available options: mongoDB, levelDB
    DBType = "mongoDB"

[Guardian]
    MnemonicFile = "keys/multiversx.mnemonic" # the path to the file containing the mnemonic phrase
    RequestTimeInSeconds = 2 # maximum timeout (in seconds) for the gas price request

[Logs]
    LogFileLifeSpanInSec = 86400 # 24h

[Antiflood]
    Enabled = false # this should be true if no other antiflood is active
    [Antiflood.WebServer]
            # SimultaneousRequests represents the number of concurrent requests accepted by the web server
            # this is a global throttler that acts on all http connections regardless of the originating source
            SimultaneousRequests = 100
            # SameSourceRequests defines how many requests are allowed from the same source in the specified
            # time frame (SameSourceResetIntervalInSec)
            SameSourceRequests = 10000
            # SameSourceResetIntervalInSec time frame between counter reset, in seconds
            SameSourceResetIntervalInSec = 1

[ServiceResolver]
    RequestTimeInSeconds = 2
    SkipTxUserSigVerify = true
    MaxTransactionsAllowedForSigning = 1000
    DelayBetweenOTPWritesInSec = 600 # the time allowed between two successive totp generation

[ShardedStorage]
    NumberOfBuckets = 4
    [ShardedStorage.Users]
        [ShardedStorage.Users.DB]
            FilePath = "UsersDB"
            Type = "LvlDB"
            BatchDelaySeconds = 1
            MaxBatchSize = 1000
            MaxOpenFiles = 10
        [ShardedStorage.Users.Cache]
            Name = "UsersCache"
            Capacity = 100000
            Type = "SizeLRU"
            SizeInBytes = 104857600 # 100MB

[TwoFactor]
    Issuer = "MultiversX"
    Digits = 6
    BackoffTimeInSeconds = 300
    MaxFailures = 3

# NativeAuthServer holds the configuration for native auth server
[NativeAuthServer]
    [NativeAuthServer.Cache]
        Name = "NativeAuthServer"
        Capacity = 100
        Type = "LRU"

[Gin]
    # ForwardedByClientIP enables parsing headers from `RemoteIPHeaders` list defined below
    ForwardedByClientIP = true

    # TrustedPlatform defines the IP header that can be trusted
    # Example: for cloudflare it can be "cf-connecting-ip", for nginx it can be "x-real-ip"
    # If there is no trusted proxy header it should be an empty string.
	TrustedPlatform = ""

    # RemoteIPHeaders defines the http headers list to check if `ForwardedByClientIP` is
    # enabled and there is no `TrustedPlatform`
	RemoteIPHeaders = [
    ]

    # RemoteIPHeaders will be checked starting with rightmost IP and checking if it is
    # trusted based on `TrustedProxies` list. If list is empty, it will not check additional
    # remote IP headers, it will get directly from `gin.RemoteAddr`
    TrustedProxies = [
    ]
