[Api]
    # The network address URL for API connection
    NetworkAddress = "https://devnet-api.multiversx.com"

[MongoDB]
    # The connection string URI for mongo client
    URI = "mongodb://localhost:27017/?replicaSet=mongoReplSet"

    # Database name to use. It has to be the same with the one provided in URI (if provided) 
    DBName = "tcs"

    # Connection timeout in seconds for mongo client
    ConnectTimeoutInSec = 60

    # Timeout in seconds for mongo operations
    OperationTimeoutInSec = 60

    # Defines the number of collections to be used with the sharding pattern
    NumUsersCollections = 4

[Redis]
    # The url used to connect to redis server
    URL = "redis://localhost:6379/0"

    # The master name for failover client
    MasterName = "mymaster"

    # The sentinel url for failover client
    SentinelUrl = "localhost:26379"

    # The redis connection type. Options: | instance | sentinel |
    # instance - it will try to connect to a single redis instance
    # sentinel - it will try to connect to redis setup with master, slave and sentinel instances
    ConnectionType = "instance"

    # Redis operation timeout in seconds
    OperationTimeoutInSec = 60

[Gin]
    # ForwardedByClientIP enables parsing headers from `RemoteIPHeaders` list defined below
    ForwardedByClientIP = true

    # TrustedPlatform defines the IP header that can be trusted
    # If there is no trusted proxy header it should be an empty string.
    TrustedPlatform = "X-Real-IP"

    # RemoteIPHeaders defines the http headers list to check if `ForwardedByClientIP` is
    # enabled and there is no `TrustedPlatform`
    RemoteIPHeaders = [
    ]

    # RemoteIPHeaders will be checked starting with rightmost IP and checking if it is
    # trusted based on `TrustedProxies` list. If list is empty, it will not check additional
    # remote IP headers, it will get directly from `gin.RemoteAddr`
    TrustedProxies = [
    ]
