[Api]
    NetworkAddress = "https://devnet-api.multiversx.com" # the network address

[MongoDB]
    URI = "mongodb://mongodb0:27017,mongodb1:27018,mongodb2:27019/?replicaSet=mongoReplSet"
    DBName = "tcs"
    ConnectTimeoutInSec = 60
    OperationTimeoutInSec = 60
