[Api]
    NetworkAddress = "https://devnet-api.multiversx.com" # the network address

[MongoDB]
    URI = "mongodb://localhost:27017/?replicaSet=rs0"
    DBName = "tcs"
    ConnectTimeoutInSec = 60
    OperationTimeoutInSec = 60
    NumIndexCollections = 4
