version: '3'

services:
    mongodb-single:
        container_name: mongodb-single
        image: mongo
        network_mode: "host"
        restart: always
        entrypoint: ["/usr/bin/mongod", "--port", "27017", "--bind_ip", "localhost,127.0.0.1", "--replSet", "mongoReplSet"]

    mongoinit:
        image: mongo
        network_mode: "host"
        depends_on:
          - mongodb-single
        restart: "no"
        entrypoint: ["bash", "-c", "sleep 5 && mongosh --host localhost:27017 --eval 'rs.initiate()'"]

    redis:
        image: redis
        network_mode: "host"
        container_name: redis-single
        command: redis-server
        ports:
            - '6379:6379'
        expose:
            - '6379'
