version: '3'

networks:
    tcs:
        driver: bridge
        ipam:
          config:
          - subnet: 172.22.0.0/24

services:
    mongodb-single:
        container_name: mongodb-single
        image: mongo
        networks:
            tcs:
              ipv4_address: 172.22.0.10
        restart: always
        ports:
            - 27017:27017
        entrypoint: ["/usr/bin/mongod", "--port", "27017", "--bind_ip", "127.0.0.1,172.22.0.10", "--replSet", "mongoReplSet"]

    mongoinit:
        image: mongo
        depends_on:
          - mongodb-single
        restart: "no"
        networks:
            tcs:
              ipv4_address: 172.22.0.2
        entrypoint: ["bash", "-c", "sleep 5 && mongosh --host 172.22.0.10:27017 --eval 'rs.initiate()'"]

    redis:
        image: redis
        container_name: redis-single
        command: redis-server
        networks:
            tcs:
              ipv4_address: 172.22.0.3
        ports:
            - '6379:6379'
        expose:
            - '6379'
