version: '3'

services:
    mongodb0:
        container_name: mongodb0
        image: mongo
        ports:
            - 27017:27017
        networks:
            - tcs
        depends_on:
            - mongodb1
            - mongodb2
        links:
          - mongodb1
          - mongodb2
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "mongoReplSet" ]

    mongoinit:
        image: mongo
        volumes:
            - ./mongodb/init.sh:/scripts/init.sh
        networks:
            - tcs
        depends_on:
          - mongodb0
        links:
          - mongodb0
        restart: "no"
        entrypoint: [ "bash", "-c", "sleep 10 && /scripts/init.sh"]

    mongodb1:
        container_name: mongodb1
        image: mongo
        ports:
            - 27018:27017
        networks:
            - tcs
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "mongoReplSet" ]

    mongodb2:
        container_name: mongodb2
        image: mongo
        ports:
            - 27019:27017
        networks:
            - tcs
        restart: always
        entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "mongoReplSet" ]

    redis:
      image: redis
      container_name: redis-single
      command: redis-server
      networks:
          - tcs
      ports:
          - '6379:6379'
      expose:
          - '6379'

networks:
    tcs:
        driver: bridge
