version: '3'

services:
    redis-cluster:
        image: 'redis:6.0-alpine'
        command: redis-cli --cluster create 172.20.0.31:6371 172.20.0.32:6372 172.20.0.33:6373 172.20.0.34:6374 172.20.0.35:6375 172.20.0.36:6376 --cluster-replicas 1 --cluster-yes
        networks:
          redis-cluster-net:
            ipv4_address: 172.20.0.30
        depends_on:
          - redis-node-1
          - redis-node-2
          - redis-node-3
          - redis-node-4
          - redis-node-5
          - redis-node-6
    redis-node-1:
        image: 'redis:6.0-alpine'
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
          - '6371:6371'
        volumes:
          - redis-node-1-data:/var/lib/redis
          - ./redis/redis-node-1.conf:/usr/local/etc/redis/redis.conf
        networks:
          redis-cluster-net:
            ipv4_address: 172.20.0.31
    redis-node-2:
        image: 'redis:6.0-alpine'
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
          - '6372:6372'
        volumes:
          - redis-node-2-data:/var/lib/redis
          - ./redis/redis-node-2.conf:/usr/local/etc/redis/redis.conf
        networks:
          redis-cluster-net:
            ipv4_address: 172.20.0.32
    redis-node-3:
        image: 'redis:6.0-alpine'
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
          - '6373:6373'
        volumes:
          - redis-node-3-data:/var/lib/redis
          - ./redis/redis-node-3.conf:/usr/local/etc/redis/redis.conf
        networks:
          redis-cluster-net:
            ipv4_address: 172.20.0.33
    redis-node-4:
        image: 'redis:6.0-alpine'
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
          - '6374:6374'
        volumes:
          - redis-node-4-data:/var/lib/redis
          - ./redis/redis-node-4.conf:/usr/local/etc/redis/redis.conf
        networks:
          redis-cluster-net:
            ipv4_address: 172.20.0.34
    redis-node-5:
        image: 'redis:6.0-alpine'
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
          - '6375:6375'
        volumes:
          - redis-node-5-data:/var/lib/redis
          - ./redis/redis-node-5.conf:/usr/local/etc/redis/redis.conf
        networks:
          redis-cluster-net:
            ipv4_address: 172.20.0.35
    redis-node-6:
        image: 'redis:6.0-alpine'
        command: redis-server /usr/local/etc/redis/redis.conf
        ports:
          - '6376:6376'
        volumes:
          - redis-node-6-data:/var/lib/redis
          - ./redis/redis-node-6.conf:/usr/local/etc/redis/redis.conf
        networks:
          redis-cluster-net:
            ipv4_address: 172.20.0.36

volumes:
  redis-node-1-data:
  redis-node-2-data:
  redis-node-3-data:
  redis-node-4-data:
  redis-node-5-data:
  redis-node-6-data:
networks:
  redis-cluster-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/24
